version: '3.7'

services:
  db:
    container_name: hello_rails_react
    image: postgres:14-alpine3.15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - hello-rails-react-data:/var/lib/postgresql/data

volumes:
  hello-rails-react-data:
